### ISSUE TITLE
这个库还在维护吗？

### ISSUE THREAD

**Issue by Veitor** [iwillwen/qiniu.js#22]
由于目前需要一个不基于Plupload的七牛上传功能，在七牛官网上显示的社区sdk中是您的这个库，但我看没有详细的使用说明文档，也好久没有更新维护了。。
都不敢用了啊。。。给个说明呗

**Comment by iwillwen** [comment]
没有更新不代表不能用啊
Sent from Mail Master
在2017年11月21日 15:39，Veitor 写道： 由于目前需要一个不基于Plupload的七牛上传功能，在七牛官网上显示的社区sdk中是您的这个库，但我看没有详细的使用说明文档，也好久没有更新维护了。。
都不敢用了啊。。。给个说明呗

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/iwillwen/qiniu.js","title":"iwillwen/qiniu.js","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/iwillwen/qiniu.js"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"这个库还在维护吗？ (#22)"}],"action":{"name":"View Issue","url":"https://github.com/iwillwen/qiniu.js/issues/22"}}}
